version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: senha_rangos
      POSTGRES_USER: postgres
      POSTGRES_DB: rangos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    restart: unless-stopped        

volumes:
  postgres_data: