version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: senha_rangos
      POSTGRES_USER: postgres
      POSTGRES_DB: rangos
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    restart: unless-stopped        

  app:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      NODE_ENV: "production"
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data: